name: Docker Image CI/CD - Beta - AspNetCore3_1

on:
  push:
    branches: [ main ]

jobs:
  # build and push
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release, prerelease"
          view_top: 1  

      - name: Set outputs
        id: vars
        run: |
          echo ::set-output name=IMAGE_NAME::plugincore-aspnetcore3-1
      
      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.last_release.outputs.tag_name }}-beta -f examples/AspNetCore3_1/Dockerfile .

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.last_release.outputs.tag_name }}-beta