name: PluginCore.IPlugins Release

on: 
  push:
    tags:
      - 'PluginCore.IPlugins-v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
        
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Zip the Build
      run: |
        cd ./src/PluginCore.IPlugins/bin/Release
        zip -r PluginCore.IPlugins-netstandard2.0.zip ./netstandard2.0/ 
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
      
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PluginCore.IPlugins-netstandard2.0.zip
        asset_name: PluginCore.IPlugins-netstandard2.0.zip
        asset_content_type: application/zip