name: PluginCore Release

on: 
  push:
    tags:
      - 'PluginCore-v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
        
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Zip the Build
      run: |
        cd ./src/PluginCore/bin/Release
        zip -r PluginCore-netcoreapp3.1.zip ./netcoreapp3.1/ 
        zip -r PluginCore-net5.0.zip ./net5.0/
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: TODO New Release.
        draft: false
        prerelease: false
      
    - name: Upload Release Asset 1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PluginCore-netcoreapp3.1.zip
        asset_name: PluginCore-netcoreapp3.1.zip
        asset_content_type: application/zip
    
    - name: Upload Release Asset 2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PluginCore-net5.0.zip
        asset_name: PluginCore-net5.0.zip
        asset_content_type: application/zip